nexx_integration.settings:
  type: mapping
  label: 'nexx Settings'
  mapping:
    channel_vocabulary:
      type: string
      label: 'The vocabulary containing channel information.'
    actor_vocabulary:
      type: string
      label: 'The vocabulary containing channel information.'
